name: BUILD_WORKFLOW_DEMO
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Flux of images updater now
        if: always()
        env:
          FLUX_WEBHOOK_URL: ${{ secrets.FLUX_WEBHOOK_URL }}
        run: |
          curl -X POST \
               -H "Content-Type: application/json" \
               --data '{}' \
               "$FLUX_WEBHOOK_URL"